language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jsblog' ]; then cd .. && eval "mv $currentfolder generator-jsblog" && cd generator-jsblog; fi

